### ISSUE TITLE
Consumo de API Latin America Dataset Repository

### ISSUE THREAD

**Issue by pablodz** [correaleyval/covid19cuba_api#9]
Usaremos su API para completar la data correspondiente a Cuba, si hay algún cambio en el formato pofavor avisarnos!

**Comment by luiscib3r** [comment]
Perfecto, esperamos agregar mas información y la posibilidad de filtrar los datos por provincias, en caso de que ocurran cambios en el nombre de los enpoints que no le permitan usar la API como se viene haciendo hasta ahora se lo notificaré oportunamente. Trataremos de mantener los mismos endpoints que tenemos hasta ahora para que no halla afectaciones.

**Comment by luiscib3r** [comment]
@ZurMaD el equipo de Covid19CubaData ha desarrollado esta API, considero que está mejor estructurada para obtener los datos en crudo y este equipo es el encargado de la recopilación y actualización de los datos con los que yo estoy trabajando, le recomiendo que revise sta nueva API.

Aqui los endpoints:

https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/affected_municipalities.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/affected_provinces.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/cases_by_mode_of_contagion.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/cases_by_nationality.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/cases_by_sex.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/comparison_of_accumulated_cases.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/distribution_by_age_ranges.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/distribution_by_nationality_of_foreign_cases.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/evolution_of_cases_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/evolution_of_deaths_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/evolution_of_recovered_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/list_of_tests_performed.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/map_data.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/note.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/resume.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/tests_by_days.json
https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/updated.json

https://covid19cuba.github.io/covid19cubadata.github.io/api/v1/all.json

**Comment by pablodz** [comment]
Gracias! Sí, vamos a ver los datos, si agregan la norma iso de Cuba como columna para una rápida identificación sería genial.

Les dejo un archivo csv con los datos del ISO 
https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/utils/iso3166-2.csv
![image](https://user-images.githubusercontent.com/28235457/78582175-8380b100-77fa-11ea-8b16-0a49353a1074.png)
